# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Build
      run: go build -v ./...
  
  deploy:
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Deploying repo to server
      run: |
        cd ../../../../../bot/bracketBot |
        git fetch |
        git pull |
        go build main.go |
        sudo systemctl restart golangapp |
        sudo systemctl status golangapp
